#!/bin/bash

# Emacs 
function install_emacs {
    EMACS_VER=27.2
    GLOBAL_VER=6.5.7
    PKGS_DIR=$(pkgs_dir)
    ThisDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
    Src=$ThisDir/../../../emacs.d
    Dest=$HOME/.emacs.d
    link $Src $Dest
    echo_message info "Install dependencies of emacs."
    # superuser_do "sudo apt-get install -y exuberant-ctags build-essential texinfo libx11-dev libxpm-dev libgif-dev openjdk-8-jdk libxaw7-dev libjpeg-dev libpng12-dev libtiff5-dev libncurses5-dev xsel libclang-3.8-dev texlive-latex-base texlive-fonts-recommended texlive-fonts-extra texlive-xetex libgnutls-dev"
    superuser_do "sudo apt-get install -y libxpm-dev libgnutls28-dev libncurses-dev libxaw7-dev xsel exuberant-ctags"
    installed_emacs=$(emacs --version | grep $EMACS_VER)
    if [[ -n $installed_emacs ]] ;then
        echo_message info "Emacs $EMACS_VER was installed."
    else 
        if [ ! -f $PKGS_DIR/emacs-${EMACS_VER}.tar.gz ];then
            cd $PKGS_DIR && curl -O http://mirrors.ustc.edu.cn/gnu/emacs/emacs-${EMACS_VER}.tar.gz
        fi
        if [ -d $PKGS_DIR/emacs-${EMACS_VER} ];then
            rm -rf $PKGS_DIR/emacs-${EMACS_VER}
        fi
        cd $PKGS_DIR && tar xvf emacs-${EMACS_VER}.tar.gz && cd emacs-${EMACS_VER} && ./configure && make && cd $PKGS_DIR/emacs-${EMACS_VER}
        echo_message info "make install emacs."
        superuser_do "sudo make install"
        rm -rf $PKGS_DIR/emacs-${EMACS_VER}
    fi
    installed_global=$(global --version | grep $GLOBAL_VER)
    if [[ -n $installed_global ]];then
        echo_message info "Global $GLOBAL_VER was installed."
    else 
        if [ ! -f $PKGS_DIR/global-${GLOBAL_VER}.tar.gz ];then
            cd $PKGS_DIR && curl -O ftp://ftp.gnu.org/pub/gnu/global/global-${GLOBAL_VER}.tar.gz
        fi
        if [ -d $PKGS_DIR/global-${GLOBAL_VER} ];then
            rm -rf $PKGS_DIR/global-${GLOBAL_VER}
        fi
        cd $PKGS_DIR && tar xvf global-${GLOBAL_VER}.tar.gz && cd global-${GLOBAL_VER} && ./configure && make && cd $PKGS_DIR/global-${GLOBAL_VER}
        superuser_do "sudo make install"
        rm -rf $PKGS_DIR/global-${GLOBAL_VER}
    fi

    # echo "export GTAGSCONF=/usr/local/share/gtags/gtags.conf" >> ~/.zshrc
    # echo "export GTAGSLABEL=ctags gtags" >> ~/.zshrc

    # echo_message info "Install ycmd for emacs with C++/C."
    # if [ ! -d "${HOME}/.emacs.d/vendor/ycmd" ];then
    #     cd $HOME/.emacs.d/vendor && git clone https://github.com/Valloric/ycmd.git ycmd
    #     superuser_do "sudo apt install clang npm"
    #     cd $HOME/.emacs.d/vendor/ycmd && git submodule update --init --recursive && python3 ./build.py --clang-completer --go-completer
    # fi
    # echo_message info ">>> ycmd installed."
    # echo_message info "Now you can execute command: ycmd in your project to generate .ycm_extra_conf.py, then enjoy it."

    echo_message info ">>> install irony."
    superuser_do "sudo apt install elpa-irony"
    echo_message success "Succeed to install emacs and ycmd."
}
