#!/bin/bash

# Install Oh-my-zsh 
function install_oh-my-zsh {
    echo_message info ">>> Install zsh."
    superuser_do "sudo apt-get install -y zsh"
    echo_message info ">>> Download and install oh-my-zsh."
    sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    ThisDir=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
    echo_message info ">>> Link zshrc.in.sh to .zshrc."
    Src=$ThisDir/../../data/config/zshrc.in.sh
    Dest=$HOME/.zshrc
    if [ -f $Dest ]; then
       rm $Dest
    fi
    link $Src $Dest
    echo_message info ">>> Change shell to zsh."
    superuser_do "chsh -s /bin/zsh" 
    echo_message info ">>> Change shell to zsh finished, Please open other terminator to continue."
}
