#!/bin/bash

# QiYeWeixin 
function install_qiyeweixin {
    PKGS_DIR=$(pkgs_dir)
    git clone https://github.com/wszqkzqk/deepin-wine-for-ubuntu.git $PKGS_DIR/deepin-wine-for-ubuntu
    wget http://packages.deepin.com/deepin/pool/non-free/d/deepin.com.weixin.work/deepin.com.weixin.work_2.8.10.2010deepin0_i386.deb -P $PKGS_DIR
    #  
    cd $PKGS_DIR/deep-wine-for-ubuntu && /bin/sh ./install_2.8.22.sh
    cd $PKGS_DIR && superuser_do "sudo dpkg -i deepin.com.weixin.work_2.8.10.2010deepin0_i386.deb"
    rm -rf $PKGS_DIR/deep-wine-for-ubuntu $PKGS_DIR/deepin.com.weixin.work_2.8.10.2010deepin0_i386.deb
    echo_message success "Succeed to install QiYe Weixin."
}
