#!/bin/bash

# shadowsocks
# http://droidyue.com/blog/2016/04/04/set-shadowsocks-proxy-for-terminal/index.html
function install_shadowsocks {
    PKGS_DIR=$(pkgs_dir)
    CONFIG_DIR=$(config_dir)
    superuser_do "apt-get install -y inkscape python-pip polipo"
    # instalation for shadowsocks in terminator
    superuser_do "pip install --upgrade git+https://github.com/shadowsocks/shadowsocks.git@master"
    if [ ! -f ${PKGS_DIR}/libsodium.tar.gz ];then
        cd ${PKGS_DIR} && wget https://download.libsodium.org/libsodium/releases/LATEST.tar.gz -O libsodium-stable.tar.gz
    fi
    cd ${PKGS_DIR} && tar xvf libsodium-stable.tar.gz && cd libsodium-stable && ./configure --prefix=/usr && make
    superuser_do "sudo make install"
    superuser_do "cp ${CONFIG_DIR}/polipo.conf /etc/polipo/config"
    superuser_do "service polipo stop"
    superuser_do "service polipo start"
    rm -rf ${PKGS_DIR}/libsodium-stable
    echo_message success "Succeed to install shadowsocks, Please configure it."
}
