#!/bin/bash

# Install zsh-tools 
function install_zsh-tools {
    echo_message info ">>> Install autojump."
    superuser_do "sudo apt-get install -y autojump"
    echo_message info ">>> Install fzf."
    git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
    ~/.fzf/install
    echo_message info ">>> Source ~/.zshrc"
    source ~/.zshrc
    echo_message info ">>> Source ~/.zshrc done, install finished."
}
