
set clipboard=unnamed  "yank and paste with the system clipboard"
set clipboard=unnamedplus

" nomal mapping
nmap s                       <Plug>(easymotion-s)
"nmap t                       <Plug>(easymotion-s2)
nmap <Leader>cp              :!xclip -i -selection clipboard % <CR><CR>

" no listchars
nmap <Leader>L               :set list!<CR>


if ! has("gui_running") 
    set t_Co=256 
endif 
" feel free to choose :set background=light for a different style 
colors peaksea

"显示行号
set nu!

syntax on
