#!/bin/bash
#
# When adding (or removing) any functions remember to update
# the 'install_custom_app' function below to reflect any changes you make

# Automatically import apps functions
function import_apps_functions {
	DIR="functions/apps"
	# iterate through the files in the 'functions/apps' folder
	for FUNCTION in $(dirname "$0")/$DIR/*; do
		if [[ -d $FUNCTION ]]; then
			continue
		elif [[ -f $FUNCTION ]]; then
			# source the function file
			. $FUNCTION
		fi
	done
}

# Install Third-Party Applications
function install_custom_app {
	NAME="Third-Party Software"
	echo_message title "Starting installation of ${NAME,,}..."
	import_apps_functions
	# Draw window
	THIRDPARTY=$(eval `resize` && whiptail \
		--notags \
		--title "Install $NAME" \
		--menu "\nWhat ${NAME,,} would you like to install?" \
		--ok-button "Install" \
		--cancel-button "Go Back" \
		$LINES $COLUMNS $(( $LINES - 12 )) \
		'install_chrome'            'Google Chrome' \
		'install_oracle_java'       'Oracle Java' \
        'install_terminator'        'terminator' \
        'install_system-monitor'    'system-monitor' \
        'install_sogou'             'sogoupinyin' \
        'install_golang'            'golang' \
        'install_oh-my-zsh'         'oh-my-zsh' \
        'install_zsh-tools'         'zsh-tools' \
        'install_emacs'             'emacs' \
        'install_wallpaper-variety' 'wallpaper-variety' \
        'install_shadowsocks'       'shadowsocks' \
        'install_go_for_it'         'go_for_it' \
        'install_qiyeweixin'        'qiyeweixin' \
		3>&1 1>&2 2>&3)

	# check exit status
	if [ $? = 0 ]; then
		echo_message header "Starting '$THIRDPARTY' function..."
		$THIRDPARTY
	else
		# Cancelled
		echo_message info "Installation of ${NAME,,} cancelled."
		main
	fi
}
