#!/bin/bash

# Install preferred apps
function install_baseapp {
	# Update the list of packages in 'data/baseapp.list' to suit your preferences
	install_from_list "preferred applications" "baseapp" main
}
